### ISSUE TITLE
Add location based value to hash used for indexing into argo

### ISSUE THREAD

**Issue by jkeck** [sul-dlss/dor-rights-auth#17]
What should we do for the hash that is returned to index the `Access Rights` facet in argo.

**Comment by jmartin-sul** [comment]
after an initial glance at this just to get a handle on it, some stray observations and questions:
* this is likely actually a dor-services issue, since that's where the code for solr doc generation lives.  i'd imagine the change we're looking to make would be in the [rightsMD to_solr method](https://github.com/sul-dlss/dor-services/blob/v5.8.1/lib/dor/datastreams/rights_metadata_ds.rb#L98), since that's where other rights-related values are added to the solr doc.
* what exactly are we looking to index here?  whether an object is location restricted or not?  or are we looking to index what specific locations allow viewing of a given object?
* are we only indexing object level information, or should file level info also be indexed?  if the latter, how is information that varies between files summarized for indexing at an object level?
* regardless of what dor-services indexes, we'll probably also want to update the [`extract_access_rights`](https://github.com/sul-dlss/dor-rights-auth/blob/v1.1.0/lib/dor/rights_auth.rb#L296) method in dor-rights-auth, since that's what actually computes the object rights summary for indexing.  dor-services really just asks a `Dor::RightsAuth` object to give a rights summary that it sticks into a field in a solr doc with minimal subsequent interpretation.  seems correct to me to continue that abstraction.

@LynnMcRae for input on what we actually need to index
@jkeck @ndushay @atz for feedback on the implementation details

**Comment by jmartin-sul** [comment]
this will also require us to keep track of the new location based items in prod so that we can make sure to reindex them once this feature is added (after which newly created or updated items will be indexed with the new code as usual).  or, we could do a full reindex of all existing items.

**Comment by jmartin-sul** [comment]
will let this sit until the actual work gets prioritized in a standup or planning mtg

**Comment by LynnMcRae** [comment]
As John and I discussed, there is a difference between how location gets folded into the hash used by extract_access_rights and the requirement to represent location as a category in the Access Rights facet.  For the latter, the requirement is to simply note the use of \<location> by adding the term "Location {value}"to the list of values shown by the facet, independent of any other rights going on with the object (that is, it is not combined in some manner like "Stanford-qualified").  Assuming it to be a simple parallel task, I would like "Agent {value}" added to the facet at the same time, again as a simple independent assertion. 

Is this sufficiently different that the ticket as expressed that it should have it's own ticket, or was this the (functional) intent of the ticket in the first place?  (it was for me but we may need the deeper engineering ticket as well).

**Comment by LynnMcRae** [comment]
see https://github.com/sul-dlss/argo/issues/753

**Comment by jmartin-sul** [comment]
as per discussion w/ @LynnMcRae yesterday/wednesday, for any given object we'll capture whether each of four access types (world, stanford, location, agent) apply at the object level as well as at the file level, and whether there's a rule qualifying the access.  in the case of location and agent, the location or agent name will also be captured.  in the case of rules, the rule text will be captured (`no-download` is currently the only rule in use).  we'll also capture a very broad single-value description of the object's access rights as a whole (`dark`, `citation`, `world`, `access_restricted`, `UNKNOWN`), and whether there are any dark files.  dor-rights-auth will return this info in its `index_elements` data structure.

in practice, dor-services will end up translating the dor-rights-auth `index_elements` info for a given object into a list of indexable human-readable statements about that object's access rights.  the list of possible statements is:

world
world (no-download)
world (file)
world (file) (no-download)

stanford
stanford (no-download)
stanford (file)
stanford (file) (no-download)

location: `location`
location: `location` (no-download)
location: `location` (file)
location: `location` (file) (no-download)

agent: `agent`
agent: `agent` (no-download)
agent: `agent` (file)
agent: `agent` (file) (no-download)

dark
dark (file)

**Comment by ndushay** [comment]
pertinent code tagging, gem updating  and releases to be done soon.   (it's an update to dor-services gem and reindexing argo)

**Comment by jmartin-sul** [comment]
dor_indexing_app and argo have been tagged and deployed to their respective stage VMs.

current plan after discussing w/ @LynnMcRae:
* test on stage
* deploy to prod
* start full reindex (will check w/ @blalbrit for timing/messaging and to make sure we're not creating unsustainable load, e.g. if heavy accessioning is also happening)
* live with an incomplete rights facet for a few days as the indexing is happening

**Comment by jmartin-sul** [comment]
discussed w/ @blalbrit and @LynnMcRae this morning, and the plan is to deploy on monday 7/25 and start the indexing then, as there's pretty heavy accessioning happening for the rest of the week, and we want to be careful not to overload fedora.

**Comment by jmartin-sul** [comment]
closing to track remaining work in sul-dlss/media#99
