### ISSUE TITLE
Update 'ars' rights metadata location with new IP (was: 171.67.132.138, new: 171.67.133.76)

### ISSUE THREAD

**Issue by hannahfrost** [sul-dlss/dor-rights-auth#35]

**Comment by blalbrit** [comment]
This ticket spawns two technical tasks

- [ ] Add IP address and identifier information to the shared_configs repo in order to associate IP addresses with location names, here: https://github.com/sul-dlss/shared_configs/blob/sul-stacks-prod/config/settings/production.yml

- [ ] The new identifier value has to be coded into dor-services so that Argo can offer locations and DOR Rights Auth can act on a location, here:
https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/rights_metadata_ds.rb#L52-L65

**Comment by jcoyne** [comment]
@blalbrit is `ars` already encoded https://github.com/sul-dlss/dor-services/blob/master/lib/dor/datastreams/rights_metadata_ds.rb#L59 ?   Is there anything left to do on the second point?

**Comment by hannahfrost** [comment]
@jcoyne It's already encoded, so nothing left to do. 

Peter and I are doing this work now.
